-- Migration MySQL pour les nouvelles fonctionnalités admin:
-- validation de devis, suivi commandes, programme immo.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS commande_lignes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  commande_id INT UNSIGNED NOT NULL,
  produit_id INT UNSIGNED NULL,
  nom_produit VARCHAR(255) NOT NULL,
  quantite INT UNSIGNED NOT NULL DEFAULT 1,
  prix_unitaire DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_ligne DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_commande_lignes_commande_id (commande_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS devis_lignes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  devis_id INT UNSIGNED NOT NULL,
  produit_id INT UNSIGNED NULL,
  nom_produit VARCHAR(255) NOT NULL,
  quantite INT UNSIGNED NOT NULL DEFAULT 1,
  prix_unitaire DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_ligne DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_devis_lignes_devis_id (devis_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE commandes
  ADD COLUMN IF NOT EXISTS devis_id INT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS total_ht DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reduction DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS frais_livraison DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_ttc DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'en_attente',
  ADD COLUMN IF NOT EXISTS statut VARCHAR(50) NOT NULL DEFAULT 'en_attente',
  ADD COLUMN IF NOT EXISTS statut_commande VARCHAR(50) NOT NULL DEFAULT 'en_attente',
  ADD COLUMN IF NOT EXISTS statut_paiement VARCHAR(50) NOT NULL DEFAULT 'non_paye',
  ADD COLUMN IF NOT EXISTS adresse_livraison TEXT NULL,
  ADD COLUMN IF NOT EXISTS region VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS departement VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS commune VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS quartier VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE devis
  ADD COLUMN IF NOT EXISTS total_ht DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_ttc DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS statut VARCHAR(50) NOT NULL DEFAULT 'en_attente',
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS adhesions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  date_naissance DATE NOT NULL,
  lieu_naissance VARCHAR(150) NOT NULL,
  adresse VARCHAR(255) NOT NULL,
  telephone VARCHAR(30) NOT NULL,
  cni VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  mode_paiement VARCHAR(100) NOT NULL,
  message TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Nouveau',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_adhesions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_notes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  adhesion_id INT UNSIGNED NOT NULL,
  admin_id INT UNSIGNED NULL,
  note TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_admin_notes_adhesion_id (adhesion_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
